# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stefan/smartRNS_UDP_updater

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stefan/smartRNS_UDP_updater

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefan/smartRNS_UDP_updater/CMakeFiles /home/stefan/smartRNS_UDP_updater/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefan/smartRNS_UDP_updater/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smartRNS_UDP_updater

# Build rule for target.
smartRNS_UDP_updater: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smartRNS_UDP_updater
.PHONY : smartRNS_UDP_updater

# fast build rule for target.
smartRNS_UDP_updater/fast:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/build
.PHONY : smartRNS_UDP_updater/fast

UDPinterface.o: UDPinterface.cpp.o
.PHONY : UDPinterface.o

# target to build an object file
UDPinterface.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/UDPinterface.cpp.o
.PHONY : UDPinterface.cpp.o

UDPinterface.i: UDPinterface.cpp.i
.PHONY : UDPinterface.i

# target to preprocess a source file
UDPinterface.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/UDPinterface.cpp.i
.PHONY : UDPinterface.cpp.i

UDPinterface.s: UDPinterface.cpp.s
.PHONY : UDPinterface.s

# target to generate assembly for a file
UDPinterface.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/UDPinterface.cpp.s
.PHONY : UDPinterface.cpp.s

configuration.o: configuration.cpp.o
.PHONY : configuration.o

# target to build an object file
configuration.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/configuration.cpp.o
.PHONY : configuration.cpp.o

configuration.i: configuration.cpp.i
.PHONY : configuration.i

# target to preprocess a source file
configuration.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/configuration.cpp.i
.PHONY : configuration.cpp.i

configuration.s: configuration.cpp.s
.PHONY : configuration.s

# target to generate assembly for a file
configuration.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/configuration.cpp.s
.PHONY : configuration.cpp.s

coreops.o: coreops.cpp.o
.PHONY : coreops.o

# target to build an object file
coreops.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/coreops.cpp.o
.PHONY : coreops.cpp.o

coreops.i: coreops.cpp.i
.PHONY : coreops.i

# target to preprocess a source file
coreops.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/coreops.cpp.i
.PHONY : coreops.cpp.i

coreops.s: coreops.cpp.s
.PHONY : coreops.s

# target to generate assembly for a file
coreops.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/coreops.cpp.s
.PHONY : coreops.cpp.s

crypto.o: crypto.cpp.o
.PHONY : crypto.o

# target to build an object file
crypto.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/crypto.cpp.o
.PHONY : crypto.cpp.o

crypto.i: crypto.cpp.i
.PHONY : crypto.i

# target to preprocess a source file
crypto.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/crypto.cpp.i
.PHONY : crypto.cpp.i

crypto.s: crypto.cpp.s
.PHONY : crypto.s

# target to generate assembly for a file
crypto.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/crypto.cpp.s
.PHONY : crypto.cpp.s

data.o: data.cpp.o
.PHONY : data.o

# target to build an object file
data.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/data.cpp.o
.PHONY : data.cpp.o

data.i: data.cpp.i
.PHONY : data.i

# target to preprocess a source file
data.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/data.cpp.i
.PHONY : data.cpp.i

data.s: data.cpp.s
.PHONY : data.s

# target to generate assembly for a file
data.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/data.cpp.s
.PHONY : data.cpp.s

dnsquery.o: dnsquery.cpp.o
.PHONY : dnsquery.o

# target to build an object file
dnsquery.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/dnsquery.cpp.o
.PHONY : dnsquery.cpp.o

dnsquery.i: dnsquery.cpp.i
.PHONY : dnsquery.i

# target to preprocess a source file
dnsquery.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/dnsquery.cpp.i
.PHONY : dnsquery.cpp.i

dnsquery.s: dnsquery.cpp.s
.PHONY : dnsquery.s

# target to generate assembly for a file
dnsquery.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/dnsquery.cpp.s
.PHONY : dnsquery.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/main.cpp.s
.PHONY : main.cpp.s

parse.o: parse.cpp.o
.PHONY : parse.o

# target to build an object file
parse.cpp.o:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/parse.cpp.o
.PHONY : parse.cpp.o

parse.i: parse.cpp.i
.PHONY : parse.i

# target to preprocess a source file
parse.cpp.i:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/parse.cpp.i
.PHONY : parse.cpp.i

parse.s: parse.cpp.s
.PHONY : parse.s

# target to generate assembly for a file
parse.cpp.s:
	$(MAKE) -f CMakeFiles/smartRNS_UDP_updater.dir/build.make CMakeFiles/smartRNS_UDP_updater.dir/parse.cpp.s
.PHONY : parse.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... smartRNS_UDP_updater"
	@echo "... UDPinterface.o"
	@echo "... UDPinterface.i"
	@echo "... UDPinterface.s"
	@echo "... configuration.o"
	@echo "... configuration.i"
	@echo "... configuration.s"
	@echo "... coreops.o"
	@echo "... coreops.i"
	@echo "... coreops.s"
	@echo "... crypto.o"
	@echo "... crypto.i"
	@echo "... crypto.s"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... dnsquery.o"
	@echo "... dnsquery.i"
	@echo "... dnsquery.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

